### ISSUE TITLE
Problems with loading PyGmod C++ module. Make sure PyGmod is installed correctly.

### ISSUE THREAD

**Issue by feelingnothing** [javabird25/PyGmod#5]
How replicate:
1. Download latest release
2. Launch Garry's Mod Singleplayer
3. Open console

Output:
[ERROR] addons/pygmod_launcher/lua/autorun/init.lua:5: [PyGmod|init.lua|ERROR] Problems with loading PyGmod C++ module. Make sure PyGmod is installed correctly. (Couldn't load module library!)
  1. error - [C]:-1
   2. unknown - addons/pygmod_launcher/lua/autorun/init.lua:5

**Comment by javabird25** [comment]
This is probably caused by a Python version mismatch, as PyGmod v0.14 works only with Python 3.7 and not with 3.8. I'll address this issue soon by packaging next PyGmod releases with Python bundled to elimitate both the requirement to install Python and any Python version mismatches.

You can fix this error now by downloading [embeddable Python 3.7 for Windows (32-bit)](https://www.python.org/ftp/python/3.8.2/python-3.8.2-embed-win32.zip) and putting the archive contents to Garry's Mod root folder (alongside `hl2.exe`).

If by any chance you're using x86-64 branch of Garry's Mod (if you don't know about it, then you don't use it), switch back to the main branch since 64-bit Garry's Mod is not yet supported.

**Comment by javabird25** [comment]
Reopening this to help other people troubleshoot until this issue is properly resolved.

**Comment by Rom3dius** [comment]
the link for embeddable Python 3.7 is actually for 3.8, might wanna fix that before you trick anyone else into downloading it

**Comment by javabird25** [comment]
> the link for embeddable Python 3.7 is actually for 3.8, might wanna fix that before you trick anyone else into downloading it

Thanks, fixed.
